"""adding feedback table relationship

Revision ID: 0bcb00098c29
Revises: 5cdf1e16e7fd
Create Date: 2024-12-22 00:40:54.895161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcb00098c29'
down_revision = '5cdf1e16e7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
