"""adding treatment column

Revision ID: 0e0fc8954bfc
Revises: 2e50c463a1f3
Create Date: 2024-12-21 10:55:52.174052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0fc8954bfc'
down_revision = '2e50c463a1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uzsakymas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uzsakymas', schema=None) as batch_op:
        batch_op.drop_column('treatment')

    # ### end Alembic commands ###
