"""Add Google OAuth fields to User model

Revision ID: a9bcfd094c3e
Revises: 6f7b3b542b0d
Create Date: 2024-12-14 22:24:54.882179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9bcfd094c3e'
down_revision = '6f7b3b542b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_picture', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_picture')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
